INSERT INTO papug_post_entity (id, content, title, date)
VALUES
    (1, 'Just adopted the cutest parrot! 🐦❤️ #ParrotLove #NewFeatheredFriend', 'Meet My New Parrot Friend', '2023-06-01 00:00:00'),
    (2, 'Having a relaxing day at home with my parrot. They really know how to chill! 😎🏠 #LazyDays', 'Chilling with My Parrot Buddy', '2023-06-02 12:30:00'),
    (3, 'Teaching my parrot some new tricks today. Can''t believe how smart they are! 🦜🎩 #SmartBird', 'Training My Clever Parrot', '2023-06-03 08:15:00'),
    (4, 'Took my parrot for a walk in the park. Met so many fellow parrot enthusiasts! 🌳🐦 #ParrotCommunity', 'Parrot Park Adventure', '2023-06-04 14:45:00'),
    (5, 'Parrots make the best companions. Their cheerful chirping always brightens up my day! ☀️🎶 #HappyVibes', 'Joyful Moments with My Parrot', '2023-06-05 09:20:00'),
    (6, 'Feeling grateful for the joy my parrot brings into my life every day. 🙏🐦❤️ #GratefulPetOwner', 'Blessed with My Parrot Companion', '2023-06-06 17:10:00'),
    (7, 'Spent the afternoon teaching my parrot to mimic some funny sounds. We had a blast! 🦜🎤 #ParrotTalks', 'Teaching My Parrot to Mimic Sounds', '2023-06-07 11:55:00'),
    (8, 'Lazy Sunday spent cuddled up with my parrot and a good book. Perfect day! 📖🛋️ #LazySundayVibes', 'Cozy Reading Time with My Parrot', '2023-06-08 19:40:00'),
    (9, 'Took my parrot to a pet-friendly cafe today. They were the center of attention! 🐦☕ #ParrotStar', 'Parrot''s Cafe Adventure', '2023-06-09 06:25:00'),
    (10, 'Parrot playtime is the highlight of my day. Their energy is contagious! 🐦🎾 #PlayfulParrot', 'Fun and Games with My Parrot', '2023-06-10 13:50:00'),
    (11, 'Celebrating my parrot''s birthday today. They bring so much joy to my life! 🎂🐦❤️ #ParrotBirthday', 'Happy Birthday to My Feathered Friend', '2023-06-11 02:05:00'),
    (12, 'Introduced my parrot to some new toys. Their curiosity is always so adorable to watch! 🦜🧸 #CuriousParrot', 'Exploring with My Inquisitive Parrot', '2023-06-12 10:30:00'),
    (13, 'Took my parrot to the beach. They weren''t sure about the sand, but the ocean fascinated them! 🏖️🌊 #ParrotBeachDay', 'Beach Adventure with My Parrot', '2023-06-13 18:55:00'),
    (14, 'Enjoying a movie night with my parrot. Snacks, a cozy blanket, and my feathered friend. 🍿📽️🐦 #MovieNight', 'Cozy Movie Night with My Parrot', '2023-06-14 07:20:00'),
    (15, 'Started clicker training with my parrot today. It''s amazing how fast they pick up new things! 🦜🖱️ #ClickerTraining', 'Clicker Training Progress with My Parrot', '2023-06-15 15:45:00'),
    (16, 'Morning cuddle sessions with my parrot are the best way to start the day. 🌅🐦❤️ #MorningBonding', 'Starting the Day with My Parrot', '2023-06-16 03:10:00'),
    (17, 'Attended a local pet expo with my parrot. They made lots of new friends! 🐾🐦❤️ #PetExpo', 'Parrot''s Day Out at the Pet Expo', '2023-06-17 10:35:00'),
    (18, 'Caught my parrot trying to have a conversation with their reflection today. Silly and adorable! 🦜🪞 #FunnyParrot', 'Amusing Encounters with My Parrot', '2023-06-18 18:00:00'),
    (19, 'Introduced my parrot to a puzzle toy. Watching them solve it was impressive and entertaining! 🦜🧩 #ParrotPuzzle', 'Parrot''s Puzzle-Solving Adventure', '2023-06-19 04:25:00'),
    (20, 'Spent quality time in the garden with my parrot. Nature seems to captivate them! 🌼🐦 #GardenBonding', 'Garden Exploration with My Parrot', '2023-06-20 11:50:00'),
    (21, 'Took my parrot to a family picnic. They enjoyed all the attention and the delicious crumbs! 🧺🐦🍔 #ParrotPicnic', 'Parrot''s Picnic Day Out', '2023-06-21 20:15:00'),
    (22, 'Started teaching my parrot some tricks. Their willingness to learn is truly inspiring! 🦜🎩 #ParrotTricks', 'Training Talents: My Parrot''s New Tricks', '2023-06-22 08:40:00'),
    (23, 'Lazy afternoon spent napping with my parrot. We both needed this relaxation time! 😴🐦 #NapTime', 'Siesta Time with My Parrot', '2023-06-23 16:05:00'),
    (24, 'Took my parrot to a local bird-watching event. They fit right in with their feathered pals! 🦜👀 #BirdWatching', 'Parrot''s Bird-Watching Experience', '2023-06-24 02:30:00'),
    (25, 'Celebrating parrot awareness day by sharing some fun facts about these wonderful birds. 🐦🌍 #ParrotAwareness', 'Happy Parrot Awareness Day!', '2023-06-25 09:55:00'),
    (26, 'Enjoying the sunset together with my parrot. These quiet moments are truly special. 🌇🐦❤️ #SunsetViews', 'Cherished Sunset with My Parrot', '2023-06-26 18:20:00'),
    (27, 'Took my parrot to the forest for the first time. Their excitement was contagious! 🌳🐦 #ForestAdventure', 'Parrot Explores the Forest', '2023-06-27 02:45:00'),
    (28, 'Attended a pet costume party with my parrot. They rocked their tiny pirate costume! 🦜🏴‍☠️ #PetCostumeParty', 'Parrot''s Pirate Party Outfit', '2023-06-28 11:10:00'),
    (29, 'Sunday spent baking bird-friendly treats for my parrot. They deserve the best! 🧁🐦 #HomemadeTreats', 'Baking Delights for My Parrot', '2023-06-29 19:35:00'),
    (30, 'Introduced my parrot to a mirror. Their reaction was a mix of curiosity and confusion! 🦜🪞 #MirrorPlay', 'Parrot''s Encounter with the Mirror', '2023-06-30 04:00:00'),
    (31, 'Just adopted the cutest parrot! 🐦❤️ #ParrotLove #NewFeatheredFriend', 'Meet My New Parrot Friend', '2023-07-01 12:25:00'),
    (32, 'Having a relaxing day at home with my parrot. They really know how to chill! 😎🏠 #LazyDays', 'Chilling with My Parrot Buddy', '2023-07-02 20:50:00'),
    (33, 'Teaching my parrot some new tricks today. Can''t believe how smart they are! 🦜🎩 #SmartBird', 'Training My Clever Parrot', '2023-07-03 05:15:00'),
    (34, 'Took my parrot for a walk in the park. Met so many fellow parrot enthusiasts! 🌳🐦 #ParrotCommunity', 'Parrot Park Adventure', '2023-07-04 13:40:00'),
    (35, 'Parrots make the best companions. Their cheerful chirping always brightens up my day! ☀️🎶 #HappyVibes', 'Joyful Moments with My Parrot', '2023-07-05 22:05:00'),
    (36, 'Feeling grateful for the joy my parrot brings into my life every day. 🙏🐦❤️ #GratefulPetOwner', 'Blessed with My Parrot Companion', '2023-07-06 06:30:00'),
    (37, 'Spent the afternoon teaching my parrot to mimic some funny sounds. We had a blast! 🦜🎤 #ParrotTalks', 'Teaching My Parrot to Mimic Sounds', '2023-07-07 14:55:00'),
    (38, 'Lazy Sunday spent cuddled up with my parrot and a good book. Perfect day! 📖🛋️ #LazySundayVibes', 'Cozy Reading Time with My Parrot', '2023-07-08 23:20:00'),
    (39, 'Took my parrot to a pet-friendly cafe today. They were the center of attention! 🐦☕ #ParrotStar', 'Parrot''s Cafe Adventure', '2023-07-09 07:45:00'),
    (40, 'Parrot playtime is the highlight of my day. Their energy is contagious! 🐦🎾 #PlayfulParrot', 'Fun and Games with My Parrot', '2023-07-10 16:10:00'),
    (41, 'Celebrating my parrot''s birthday today. They bring so much joy to my life! 🎂🐦❤️ #ParrotBirthday', 'Happy Birthday to My Feathered Friend', '2023-07-11 00:35:00'),
    (42, 'Introduced my parrot to some new toys. Their curiosity is always so adorable to watch! 🦜🧸 #CuriousParrot', 'Exploring with My Inquisitive Parrot', '2023-07-12 09:00:00'),
    (43, 'Took my parrot to the beach. They weren''t sure about the sand, but the ocean fascinated them! 🏖️🌊 #ParrotBeachDay', 'Beach Adventure with My Parrot', '2023-07-13 17:25:00'),
    (44, 'Enjoying a movie night with my parrot. Snacks, a cozy blanket, and my feathered friend. 🍿📽️🐦 #MovieNight', 'Cozy Movie Night with My Parrot', '2023-07-14 01:50:00'),
    (45, 'Started clicker training with my parrot today. It''s amazing how fast they pick up new things! 🦜🖱️ #ClickerTraining', 'Clicker Training Progress with My Parrot', '2023-07-15 10:15:00'),
    (46, 'Morning cuddle sessions with my parrot are the best way to start the day. 🌅🐦❤️ #MorningBonding', 'Starting the Day with My Parrot', '2023-07-16 18:40:00'),
    (47, 'Attended a local pet expo with my parrot. They made lots of new friends! 🐾🐦❤️ #PetExpo', 'Parrot''s Day Out at the Pet Expo', '2023-07-17 03:05:00'),
    (48, 'Caught my parrot trying to have a conversation with their reflection today. Silly and adorable! 🦜🪞 #FunnyParrot', 'Amusing Encounters with My Parrot', '2023-07-18 11:30:00'),
    (49, 'Introduced my parrot to a puzzle toy. Watching them solve it was impressive and entertaining! 🦜🧩 #ParrotPuzzle', 'Parrot''s Puzzle-Solving Adventure', '2023-07-19 19:55:00'),
    (50, 'Spent quality time in the garden with my parrot. Nature seems to captivate them! 🌼🐦 #GardenBonding', 'Garden Exploration with My Parrot', '2023-07-20 04:20:00'),
    (51, 'Took my parrot to a family picnic. They enjoyed all the attention and the delicious crumbs! 🧺🐦🍔 #ParrotPicnic', 'Parrot''s Picnic Day Out', '2023-07-21 12:45:00'),
    (52, 'Started teaching my parrot some tricks. Their willingness to learn is truly inspiring! 🦜🎩 #ParrotTricks', 'Training Talents: My Parrot''s New Tricks', '2023-07-22 21:10:00'),
    (53, 'Lazy afternoon spent napping with my parrot. We both needed this relaxation time! 😴🐦 #NapTime', 'Siesta Time with My Parrot', '2023-07-23 05:35:00'),
    (54, 'Took my parrot to a local bird-watching event. They fit right in with their feathered pals! 🦜👀 #BirdWatching', 'Parrot''s Bird-Watching Experience', '2023-07-24 14:00:00'),
    (55, 'Celebrating parrot awareness day by sharing some fun facts about these wonderful birds. 🐦🌍 #ParrotAwareness', 'Happy Parrot Awareness Day!', '2023-07-25 22:25:00'),
    (56, 'Enjoying the sunset together with my parrot. These quiet moments are truly special. 🌇🐦❤️ #SunsetViews', 'Cherished Sunset with My Parrot', '2023-07-26 06:50:00'),
    (57, 'Took my parrot to the forest for the first time. Their excitement was contagious! 🌳🐦 #ForestAdventure', 'Parrot Explores the Forest', '2023-07-27 15:15:00'),
    (58, 'Attended a pet costume party with my parrot. They rocked their tiny pirate costume! 🦜🏴‍☠️ #PetCostumeParty', 'Parrot''s Pirate Party Outfit', '2023-07-28 23:40:00'),
    (59, 'Sunday spent baking bird-friendly treats for my parrot. They deserve the best! 🧁🐦 #HomemadeTreats', 'Baking Delights for My Parrot', '2023-07-29 08:05:00'),
    (60, 'Introduced my parrot to a mirror. Their reaction was a mix of curiosity and confusion! 🦜🪞 #MirrorPlay', 'Parrot''s Encounter with the Mirror', '2023-07-30 16:30:00'),
    (61, 'Just adopted the cutest parrot! 🐦❤️ #ParrotLove #NewFeatheredFriend', 'Meet My New Parrot Friend', '2023-08-01 00:55:00'),
    (62, 'Having a relaxing day at home with my parrot. They really know how to chill! 😎🏠 #LazyDays', 'Chilling with My Parrot Buddy', '2023-08-02 09:20:00'),
    (63, 'Teaching my parrot some new tricks today. Can''t believe how smart they are! 🦜🎩 #SmartBird', 'Training My Clever Parrot', '2023-08-03 17:45:00'),
    (64, 'Took my parrot for a walk in the park. Met so many fellow parrot enthusiasts! 🌳🐦 #ParrotCommunity', 'Parrot Park Adventure', '2023-08-04 02:10:00'),
    (65, 'Parrots make the best companions. Their cheerful chirping always brightens up my day! ☀️🎶 #HappyVibes', 'Joyful Moments with My Parrot', '2023-08-05 10:35:00'),
    (66, 'Feeling grateful for the joy my parrot brings into my life every day. 🙏🐦❤️ #GratefulPetOwner', 'Blessed with My Parrot Companion', '2023-08-06 19:00:00'),
    (67, 'Spent the afternoon teaching my parrot to mimic some funny sounds. We had a blast! 🦜🎤 #ParrotTalks', 'Teaching My Parrot to Mimic Sounds', '2023-08-07 03:25:00'),
    (68, 'Lazy Sunday spent cuddled up with my parrot and a good book. Perfect day! 📖🛋️ #LazySundayVibes', 'Cozy Reading Time with My Parrot', '2023-08-08 11:50:00'),
    (69, 'Took my parrot to a pet-friendly cafe today. They were the center of attention! 🐦☕ #ParrotStar', 'Parrot''s Cafe Adventure', '2023-08-09 20:15:00'),
    (70, 'Parrot playtime is the highlight of my day. Their energy is contagious! 🐦🎾 #PlayfulParrot', 'Fun and Games with My Parrot', '2023-08-10 04:40:00'),
    (71, 'Celebrating my parrot''s birthday today. They bring so much joy to my life! 🎂🐦❤️ #ParrotBirthday', 'Happy Birthday to My Feathered Friend', '2023-08-11 13:05:00'),
    (72, 'Introduced my parrot to some new toys. Their curiosity is always so adorable to watch! 🦜🧸 #CuriousParrot', 'Exploring with My Inquisitive Parrot', '2023-08-12 21:30:00'),
    (73, 'Took my parrot to the beach. They weren''t sure about the sand, but the ocean fascinated them! 🏖️🌊 #ParrotBeachDay', 'Beach Adventure with My Parrot', '2023-08-13 05:55:00'),
    (74, 'Enjoying a movie night with my parrot. Snacks, a cozy blanket, and my feathered friend. 🍿📽️🐦 #MovieNight', 'Cozy Movie Night with My Parrot', '2023-08-14 14:20:00'),
    (75, 'Started clicker training with my parrot today. It''s amazing how fast they pick up new things! 🦜🖱️ #ClickerTraining', 'Clicker Training Progress with My Parrot', '2023-08-15 22:45:00'),
    (76, 'Morning cuddle sessions with my parrot are the best way to start the day. 🌅🐦❤️ #MorningBonding', 'Starting the Day with My Parrot', '2023-08-16 07:10:00'),
    (77, 'Attended a local pet expo with my parrot. They made lots of new friends! 🐾🐦❤️ #PetExpo', 'Parrot''s Day Out at the Pet Expo', '2023-08-17 15:35:00'),
    (78, 'Caught my parrot trying to have a conversation with their reflection today. Silly and adorable! 🦜🪞 #FunnyParrot', 'Amusing Encounters with My Parrot', '2023-08-18 00:00:00'),
    (79, 'Introduced my parrot to a puzzle toy. Watching them solve it was impressive and entertaining! 🦜🧩 #ParrotPuzzle', 'Parrot''s Puzzle-Solving Adventure', '2023-08-19 08:25:00'),
    (80, 'Spent quality time in the garden with my parrot. Nature seems to captivate them! 🌼🐦 #GardenBonding', 'Garden Exploration with My Parrot', '2023-08-20 16:50:00'),
    (81, 'Took my parrot to a family picnic. They enjoyed all the attention and the delicious crumbs! 🧺🐦🍔 #ParrotPicnic', 'Parrot''s Picnic Day Out', '2023-08-21 01:15:00'),
    (82, 'Started teaching my parrot some tricks. Their willingness to learn is truly inspiring! 🦜🎩 #ParrotTricks', 'Training Talents: My Parrot''s New Tricks', '2023-08-22 09:40:00'),
    (83, 'Lazy afternoon spent napping with my parrot. We both needed this relaxation time! 😴🐦 #NapTime', 'Siesta Time with My Parrot', '2023-08-23 18:05:00'),
    (84, 'Took my parrot to a local bird-watching event. They fit right in with their feathered pals! 🦜👀 #BirdWatching', 'Parrot''s Bird-Watching Experience', '2023-08-24 02:30:00'),
    (85, 'Celebrating parrot awareness day by sharing some fun facts about these wonderful birds. 🐦🌍 #ParrotAwareness', 'Happy Parrot Awareness Day!', '2023-08-25 10:55:00'),
    (86, 'Enjoying the sunset together with my parrot. These quiet moments are truly special. 🌇🐦❤️ #SunsetViews', 'Cherished Sunset with My Parrot', '2023-08-26 19:20:00'),
    (87, 'Took my parrot to the forest for the first time. Their excitement was contagious! 🌳🐦 #ForestAdventure', 'Parrot Explores the Forest', '2023-08-27 03:45:00'),
    (88, 'Attended a pet costume party with my parrot. They rocked their tiny pirate costume! 🦜🏴‍☠️ #PetCostumeParty', 'Parrot''s Pirate Party Outfit', '2023-08-28 12:10:00'),
    (89, 'Sunday spent baking bird-friendly treats for my parrot. They deserve the best! 🧁🐦 #HomemadeTreats', 'Baking Delights for My Parrot', '2023-08-29 20:35:00'),
    (90, 'Introduced my parrot to a mirror. Their reaction was a mix of curiosity and confusion! 🦜🪞 #MirrorPlay', 'Parrot''s Encounter with the Mirror', '2023-08-30 05:00:00')
    ON CONFLICT (id) DO NOTHING;
