INSERT INTO papug_post_entity (id, content, title)
VALUES
    (1, 'Just adopted the cutest papug! 🐦❤️ #PapugLove #NewFeatheredFriend', 'Meet My New Papug Friend'),
    (2, 'Having a relaxing day at home with my papug. They really know how to chill! 😎🏠 #LazyDays', 'Chilling with My Papug Buddy'),
    (3, 'Teaching my papug some new tricks today. Can''t believe how smart they are! 🦜🎩 #SmartBird', 'Training My Clever Papug'),
    (4, 'Took my papug for a walk in the park. Met so many fellow papug enthusiasts! 🌳🐦 #PapugCommunity', 'Papug Park Adventure'),
    (5, 'Papugs make the best companions. Their cheerful chirping always brightens up my day! ☀️🎶 #HappyVibes', 'Joyful Moments with My Papug'),
    (6, 'Feeling grateful for the joy my papug brings into my life every day. 🙏🐦❤️ #GratefulPetOwner', 'Blessed with My Papug Companion'),
    (7, 'Spent the afternoon teaching my papug to mimic some funny sounds. We had a blast! 🦜🎤 #PapugTalks', 'Teaching My Papug to Mimic Sounds'),
    (8, 'Lazy Sunday spent cuddled up with my papug and a good book. Perfect day! 📖🛋️ #LazySundayVibes', 'Cozy Reading Time with My Papug'),
    (9, 'Took my papug to a pet-friendly cafe today. They were the center of attention! 🐦☕ #PapugStar', 'Papug''s Cafe Adventure'),
    (10, 'Papug playtime is the highlight of my day. Their energy is contagious! 🐦🎾 #PlayfulPapug', 'Fun and Games with My Papug'),
    (11, 'Celebrating my papug''s birthday today. They bring so much joy to my life! 🎂🐦❤️ #PapugBirthday', 'Happy Birthday to My Feathered Friend'),
    (12, 'Introduced my papug to some new toys. Their curiosity is always so adorable to watch! 🦜🧸 #CuriousPapug', 'Exploring with My Inquisitive Papug'),
    (13, 'Took my papug to the beach. They weren''t sure about the sand, but the ocean fascinated them! 🏖️🌊 #PapugBeachDay', 'Beach Adventure with My Papug'),
    (14, 'Enjoying a movie night with my papug. Snacks, a cozy blanket, and my feathered friend. 🍿📽️🐦 #MovieNight', 'Cozy Movie Night with My Papug'),
    (15, 'Started clicker training with my papug today. It''s amazing how fast they pick up new things! 🦜🖱️ #ClickerTraining', 'Clicker Training Progress with My Papug'),
    (16, 'Morning cuddle sessions with my papug are the best way to start the day. 🌅🐦❤️ #MorningBonding', 'Starting the Day with My Papug'),
    (17, 'Attended a local pet expo with my papug. They made lots of new friends! 🐾🐦❤️ #PetExpo', 'Papug''s Day Out at the Pet Expo'),
    (18, 'Caught my papug trying to have a conversation with their reflection today. Silly and adorable! 🦜🪞 #FunnyPapug', 'Amusing Encounters with My Papug'),
    (19, 'Introduced my papug to a puzzle toy. Watching them solve it was impressive and entertaining! 🦜🧩 #PapugPuzzle', 'Papug''s Puzzle-Solving Adventure'),
    (20, 'Spent quality time in the garden with my papug. Nature seems to captivate them! 🌼🐦 #GardenBonding', 'Garden Exploration with My Papug'),
    (21, 'Took my papug to a family picnic. They enjoyed all the attention and the delicious crumbs! 🧺🐦🍔 #PapugPicnic', 'Papug''s Picnic Day Out'),
    (22, 'Started teaching my papug some tricks. Their willingness to learn is truly inspiring! 🦜🎩 #PapugTricks', 'Training Talents: My Papug''s New Tricks'),
    (23, 'Lazy afternoon spent napping with my papug. We both needed this relaxation time! 😴🐦 #NapTime', 'Siesta Time with My Papug'),
    (24, 'Took my papug to a local bird-watching event. They fit right in with their feathered pals! 🦜👀 #BirdWatching', 'Papug''s Bird-Watching Experience'),
    (25, 'Celebrating papug awareness day by sharing some fun facts about these wonderful birds. 🐦🌍 #PapugAwareness', 'Happy Papug Awareness Day!'),
    (26, 'Enjoying the sunset together with my papug. These quiet moments are truly special. 🌇🐦❤️ #SunsetViews', 'Cherished Sunset with My Papug'),
    (27, 'Took my papug to the forest for the first time. Their excitement was contagious! 🌳🐦 #ForestAdventure', 'Papug Explores the Forest'),
    (28, 'Attended a pet costume party with my papug. They rocked their tiny pirate costume! 🦜🏴‍☠️ #PetCostumeParty', 'Papug''s Pirate Party Outfit'),
    (29, 'Sunday spent baking bird-friendly treats for my papug. They deserve the best! 🧁🐦 #HomemadeTreats', 'Baking Delights for My Papug'),
    (30, 'Introduced my papug to a mirror. Their reaction was a mix of curiosity and confusion! 🦜🪞 #MirrorPlay', 'Papug''s Encounter with the Mirror')
    ON CONFLICT (id) DO NOTHING;
